language: node_js
node_js:
  - "12.18.3"
  - "14.8.0"
install: 
  - npm install
script:
  - npm run build
  - npm test
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  on:
    tags: true
    branch: master
  api_key: $NPM_TOKEN